import { Prisma, Country, Region, Category } from "@prisma/client";
import { Countries, CountryCode, RegionCode } from "./types";

export const REGIONS = {
  NORTHERN_AFRICA: {
    name: "Northern Africa",
    code: RegionCode.NA,
    countries: [
      CountryCode.DZ,
      CountryCode.EG,
      CountryCode.LY,
      CountryCode.MA,
      CountryCode.SD,
      CountryCode.TN,
      // CountryCode.EH,
    ],
  },
  SUB_SAHARAN_AFRICA: {
    name: "Sub-Saharan Africa",
    code: RegionCode.SSA,
    countries: [
      CountryCode.BF,
      CountryCode.BJ,
      CountryCode.CI,
      CountryCode.CV,
      CountryCode.GH,
      CountryCode.GM,
      CountryCode.GN,
      CountryCode.GW,
      CountryCode.LR,
      CountryCode.ML,
      CountryCode.MR,
      CountryCode.NE,
      CountryCode.NG,
      // CountryCode.SH,
      CountryCode.SL,
      CountryCode.SN,
      CountryCode.TG,
    ],
  },
  EASTERN_AFRICA: {
    name: "Eastern Africa",
    code: RegionCode.EA,
    countries: [
      CountryCode.BI,
      CountryCode.DJ,
      CountryCode.ER,
      CountryCode.ET,
      CountryCode.KE,
      CountryCode.KM,
      CountryCode.MG,
      CountryCode.MU,
      CountryCode.MW,
      CountryCode.MZ,
      // CountryCode.RE,
      CountryCode.RW,
      CountryCode.SC,
      CountryCode.SO,
      CountryCode.TZ,
      CountryCode.UG,
      // CountryCode.YT,
      CountryCode.ZM,
      CountryCode.ZW,
    ],
  },
  CENTRAL_AFRICA: {
    name: "Central Africa",
    code: RegionCode.CA,
    countries: [
      CountryCode.AO,
      CountryCode.CD,
      CountryCode.CF,
      CountryCode.CG,
      CountryCode.CM,
      CountryCode.GA,
      CountryCode.GQ,
      CountryCode.ST,
      CountryCode.TD,
    ],
  },
  SOUTHERN_AFRICA: {
    name: "Southern Africa",
    code: RegionCode.SA,
    countries: [
      CountryCode.BW,
      CountryCode.LS,
      CountryCode.NA,
      CountryCode.SZ,
      CountryCode.ZA,
    ],
  },
  WESTERN_AFRICA: {
    name: "Western Africa",
    code: RegionCode.WA,
    countries: [
      CountryCode.BJ,
      CountryCode.BF,
      CountryCode.CV,
      CountryCode.CI,
      CountryCode.GH,
      CountryCode.GM,
      CountryCode.GN,
      CountryCode.GW,
      CountryCode.LR,
      CountryCode.ML,
      CountryCode.MR,
      CountryCode.NE,
      CountryCode.NG,
      // CountryCode.SH,
      CountryCode.SL,
      CountryCode.SN,
      CountryCode.TG,
    ],
  },
};

export const COUNTRIES: Countries = {
  ALGERIA: { name: "Algeria", code: CountryCode.DZ },
  ANGOLA: { name: "Angola", code: CountryCode.AO },
  BENIN: { name: "Benin", code: CountryCode.BJ },
  BOTSWANA: { name: "Botswana", code: CountryCode.BW },
  BURKINA_FASO: { name: "Burkina Faso", code: CountryCode.BF },
  BURUNDI: { name: "Burundi", code: CountryCode.BI },
  CAPE_VERDE: { name: "Cape Verde", code: CountryCode.CV },
  CAMEROON: { name: "Cameroon", code: CountryCode.CM },
  CENTRAL_AFRICAN_REPUBLIC: {
    name: "Central African Republic",
    code: CountryCode.CF,
  },
  CHAD: { name: "Chad", code: CountryCode.TD },
  COMOROS: { name: "Comoros", code: CountryCode.KM },
  CONGO: { name: "Congo", code: CountryCode.CG },
  DEMOCRATIC_REPUBLIC_OF_THE_CONGO: {
    name: "Democratic Republic of the Congo",
    code: CountryCode.CD,
  },
  DJIBOUTI: { name: "Djibouti", code: CountryCode.DJ },
  EGYPT: { name: "Egypt", code: CountryCode.EG },
  EQUATORIAL_GUINEA: { name: "Equatorial Guinea", code: CountryCode.GQ },
  ERITREA: { name: "Eritrea", code: CountryCode.ER },
  ESWATINI: { name: "Eswatini", code: CountryCode.SZ },
  ETHIOPIA: { name: "Ethiopia", code: CountryCode.ET },
  GABON: { name: "Gabon", code: CountryCode.GA },
  GAMBIA: { name: "Gambia", code: CountryCode.GM },
  GHANA: { name: "Ghana", code: CountryCode.GH },
  GUINEA: { name: "Guinea", code: CountryCode.GN },
  GUINEA_BISSAU: { name: "Guinea-Bissau", code: CountryCode.GW },
  IVORY_COAST: { name: "Ivory Coast", code: CountryCode.CI },
  KENYA: { name: "Kenya", code: CountryCode.KE },
  LESOTHO: { name: "Lesotho", code: CountryCode.LS },
  LIBERIA: { name: "Liberia", code: CountryCode.LR },
  LIBYA: { name: "Libya", code: CountryCode.LY },
  MADAGASCAR: { name: "Madagascar", code: CountryCode.MG },
  MALAWI: { name: "Malawi", code: CountryCode.MW },
  MALI: { name: "Mali", code: CountryCode.ML },
  MAURITANIA: { name: "Mauritania", code: CountryCode.MR },
  MAURITIUS: { name: "Mauritius", code: CountryCode.MU },
  MOROCCO: { name: "Morocco", code: CountryCode.MA },
  MOZAMBIQUE: { name: "Mozambique", code: CountryCode.MZ },
  NAMIBIA: { name: "Namibia", code: CountryCode.NA },
  NIGER: { name: "Niger", code: CountryCode.NE },
  NIGERIA: { name: "Nigeria", code: CountryCode.NG },
  RWANDA: { name: "Rwanda", code: CountryCode.RW },
  SAO_TOME_AND_PRINCIPE: {
    name: "Sao Tome and Principe",
    code: CountryCode.ST,
  },
  SENEGAL: { name: "Senegal", code: CountryCode.SN },
  SEYCHELLES: { name: "Seychelles", code: CountryCode.SC },
  SIERRA_LEONE: { name: "Sierra Leone", code: CountryCode.SL },
  SOMALIA: { name: "Somalia", code: CountryCode.SO },
  SOUTH_AFRICA: { name: "South Africa", code: CountryCode.ZA },
  SOUTH_SUDAN: { name: "South Sudan", code: CountryCode.SS },
  SUDAN: { name: "Sudan", code: CountryCode.SD },
  TANZANIA: { name: "Tanzania", code: CountryCode.TZ },
  TOGO: { name: "Togo", code: CountryCode.TG },
  TUNISIA: { name: "Tunisia", code: CountryCode.TN },
  UGANDA: { name: "Uganda", code: CountryCode.UG },
  ZAMBIA: { name: "Zambia", code: CountryCode.ZM },
  ZIMBABWE: { name: "Zimbabwe", code: CountryCode.ZW },
};

export const SEED_PROVERBS: Prisma.ProverbCreateInput[] = [
  {
    text: "If you do not know death, look at the grave",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "When the lion cannot find meat, it eats grass",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "One whose seeds have not sprouted does not give up planting",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.SUCCESS,
  },
  {
    text: "A king’s child is a slave elsewhere",
    country: Country.ZIMBABWE,
    region: Region.SOUTHERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "Prepare now for the solutions of tomorrow",
    country: Country.CONGO,
    region: Region.CENTRAL_AFRICA,
    category: Category.SUCCESS,
  },
  {
    text: "A snake that you can see does not bite",
    country: Country.MOZAMBIQUE,
    region: Region.SOUTHERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "The words of the elders become sweet some day",
    country: Country.MALAWI,
    region: Region.SOUTHERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "More precious than our children are the children of our children",
    country: Country.EGYPT,
    region: Region.NORTHERN_AFRICA,
    category: Category.LOVE,
  },
  {
    text: "Unity is the real thing",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "A bird that allows itself to be caught will find a way of escaping",
    country: Country.CAMEROON,
    region: Region.CENTRAL_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "If you are ugly you must either learn to dance or make love",
    country: Country.ZIMBABWE,
    region: Region.SOUTHERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "The strong bull is overcome when it limps",
    country: Country.ETHIOPIA,
    region: Region.EASTERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "Water that has been begged for does not quench the thirst",
    country: Country.UGANDA,
    region: Region.EASTERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "The humble pay for the mistakes of their leaders",
    country: Country.TANZANIA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "No tattoo is made without blood",
    country: Country.MOZAMBIQUE,
    region: Region.SOUTHERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "He who learns, teaches",
    country: Country.ETHIOPIA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "Wisdom is like a baobab tree; no one individual can embrace it",
    country: Country.GHANA,
    region: Region.WESTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "The fool speaks, the wise man listens",
    country: Country.ETHIOPIA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "In the moment of crisis, the wise build bridges, and the foolish build dams",
    country: Country.NIGERIA,
    region: Region.WESTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "A wise person will always find a way",
    country: Country.TANZANIA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "Nobody is born wise",
    country: Country.EGYPT,
    region: Region.NORTHERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "A man who uses force is afraid of reasoning",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.WISDOM,
  },
  {
    text: "Peace is costly but it is worth the expense",
    country: Country.KENYA,
    region: Region.EASTERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "When there is peace in the country, the chief does not carry a shield",
    country: Country.UGANDA,
    region: Region.EASTERN_AFRICA,
    category: Category.LIFE,
  },
  {
    text: "Speak softly and carry a big stick; you will go far",
    country: Country.NIGERIA,
    region: Region.WESTERN_AFRICA,
    category: Category.SUCCESS,
  },
];

export const LOADING_TEXT: string[] = [
  "Gathering wisdom...",
  "Consulting the elders...",
  "Unraveling ancient truths...",
  "Sifting through the sands of time...",
  "Weaving the fabric of knowledge...",
  "Carving out proverbs from the Baobab tree...",
  "Brewing a pot of ancestral wisdom...",
  "Following the footsteps of our forefathers...",
  "Deciphering the old scrolls...",
  "Drawing water from the well of wisdom...",
];
