import { Country } from "@prisma/client";
import {
  Countries,
  CountryCode,
  Region as RegionType,
  RegionCode,
} from "./types";

export const REGIONS = {
  NORTHERN_AFRICA: {
    name: "Northern Africa",
    code: RegionCode.NA,
    countries: [
      CountryCode.DZ,
      CountryCode.EG,
      CountryCode.LY,
      CountryCode.MA,
      CountryCode.SD,
      CountryCode.TN,
      // CountryCode.EH,
    ],
  },
  SUB_SAHARAN_AFRICA: {
    name: "Sub-Saharan Africa",
    code: RegionCode.SSA,
    countries: [
      CountryCode.BF,
      CountryCode.BJ,
      CountryCode.CI,
      CountryCode.CV,
      CountryCode.GH,
      CountryCode.GM,
      CountryCode.GN,
      CountryCode.GW,
      CountryCode.LR,
      CountryCode.ML,
      CountryCode.MR,
      CountryCode.NE,
      CountryCode.NG,
      // CountryCode.SH,
      CountryCode.SL,
      CountryCode.SN,
      CountryCode.TG,
    ],
  },
  EASTERN_AFRICA: {
    name: "Eastern Africa",
    code: RegionCode.EA,
    countries: [
      CountryCode.BI,
      CountryCode.DJ,
      CountryCode.ER,
      CountryCode.ET,
      CountryCode.KE,
      CountryCode.KM,
      CountryCode.MG,
      CountryCode.MU,
      CountryCode.MW,
      CountryCode.MZ,
      // CountryCode.RE,
      CountryCode.RW,
      CountryCode.SC,
      CountryCode.SO,
      CountryCode.TZ,
      CountryCode.UG,
      // CountryCode.YT,
      CountryCode.ZM,
      CountryCode.ZW,
    ],
  },
  CENTRAL_AFRICA: {
    name: "Central Africa",
    code: RegionCode.CA,
    countries: [
      CountryCode.AO,
      CountryCode.CD,
      CountryCode.CF,
      CountryCode.CG,
      CountryCode.CM,
      CountryCode.GA,
      CountryCode.GQ,
      CountryCode.ST,
      CountryCode.TD,
    ],
  },
  SOUTHERN_AFRICA: {
    name: "Southern Africa",
    code: RegionCode.SA,
    countries: [
      CountryCode.BW,
      CountryCode.LS,
      CountryCode.NA,
      CountryCode.SZ,
      CountryCode.ZA,
    ],
  },
  WESTERN_AFRICA: {
    name: "Western Africa",
    code: RegionCode.WA,
    countries: [
      CountryCode.BJ,
      CountryCode.BF,
      CountryCode.CV,
      CountryCode.CI,
      CountryCode.GH,
      CountryCode.GM,
      CountryCode.GN,
      CountryCode.GW,
      CountryCode.LR,
      CountryCode.ML,
      CountryCode.MR,
      CountryCode.NE,
      CountryCode.NG,
      // CountryCode.SH,
      CountryCode.SL,
      CountryCode.SN,
      CountryCode.TG,
    ],
  },
};

export const COUNTRIES: Countries = {
  ALGERIA: { name: "Algeria", code: CountryCode.DZ },
  ANGOLA: { name: "Angola", code: CountryCode.AO },
  BENIN: { name: "Benin", code: CountryCode.BJ },
  BOTSWANA: { name: "Botswana", code: CountryCode.BW },
  BURKINA_FASO: { name: "Burkina Faso", code: CountryCode.BF },
  BURUNDI: { name: "Burundi", code: CountryCode.BI },
  CAPE_VERDE: { name: "Cape Verde", code: CountryCode.CV },
  CAMEROON: { name: "Cameroon", code: CountryCode.CM },
  CENTRAL_AFRICAN_REPUBLIC: {
    name: "Central African Republic",
    code: CountryCode.CF,
  },
  CHAD: { name: "Chad", code: CountryCode.TD },
  COMOROS: { name: "Comoros", code: CountryCode.KM },
  CONGO: { name: "Congo", code: CountryCode.CG },
  DEMOCRATIC_REPUBLIC_OF_THE_CONGO: {
    name: "Democratic Republic of the Congo",
    code: CountryCode.CD,
  },
  DJIBOUTI: { name: "Djibouti", code: CountryCode.DJ },
  EGYPT: { name: "Egypt", code: CountryCode.EG },
  EQUATORIAL_GUINEA: { name: "Equatorial Guinea", code: CountryCode.GQ },
  ERITREA: { name: "Eritrea", code: CountryCode.ER },
  ESWATINI: { name: "Eswatini", code: CountryCode.SZ },
  ETHIOPIA: { name: "Ethiopia", code: CountryCode.ET },
  GABON: { name: "Gabon", code: CountryCode.GA },
  GAMBIA: { name: "Gambia", code: CountryCode.GM },
  GHANA: { name: "Ghana", code: CountryCode.GH },
  GUINEA: { name: "Guinea", code: CountryCode.GN },
  GUINEA_BISSAU: { name: "Guinea-Bissau", code: CountryCode.GW },
  IVORY_COAST: { name: "Ivory Coast", code: CountryCode.CI },
  KENYA: { name: "Kenya", code: CountryCode.KE },
  LESOTHO: { name: "Lesotho", code: CountryCode.LS },
  LIBERIA: { name: "Liberia", code: CountryCode.LR },
  LIBYA: { name: "Libya", code: CountryCode.LY },
  MADAGASCAR: { name: "Madagascar", code: CountryCode.MG },
  MALAWI: { name: "Malawi", code: CountryCode.MW },
  MALI: { name: "Mali", code: CountryCode.ML },
  MAURITANIA: { name: "Mauritania", code: CountryCode.MR },
  MAURITIUS: { name: "Mauritius", code: CountryCode.MU },
  MOROCCO: { name: "Morocco", code: CountryCode.MA },
  MOZAMBIQUE: { name: "Mozambique", code: CountryCode.MZ },
  NAMIBIA: { name: "Namibia", code: CountryCode.NA },
  NIGER: { name: "Niger", code: CountryCode.NE },
  NIGERIA: { name: "Nigeria", code: CountryCode.NG },
  RWANDA: { name: "Rwanda", code: CountryCode.RW },
  SAO_TOME_AND_PRINCIPE: {
    name: "Sao Tome and Principe",
    code: CountryCode.ST,
  },
  SENEGAL: { name: "Senegal", code: CountryCode.SN },
  SEYCHELLES: { name: "Seychelles", code: CountryCode.SC },
  SIERRA_LEONE: { name: "Sierra Leone", code: CountryCode.SL },
  SOMALIA: { name: "Somalia", code: CountryCode.SO },
  SOUTH_AFRICA: { name: "South Africa", code: CountryCode.ZA },
  SOUTH_SUDAN: { name: "South Sudan", code: CountryCode.SS },
  SUDAN: { name: "Sudan", code: CountryCode.SD },
  TANZANIA: { name: "Tanzania", code: CountryCode.TZ },
  TOGO: { name: "Togo", code: CountryCode.TG },
  TUNISIA: { name: "Tunisia", code: CountryCode.TN },
  UGANDA: { name: "Uganda", code: CountryCode.UG },
  ZAMBIA: { name: "Zambia", code: CountryCode.ZM },
  ZIMBABWE: { name: "Zimbabwe", code: CountryCode.ZW },
};
