import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "African Proverbs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/proverbs">Proverbs</Link>
            </li>
            <li>
              <Link href="/admin/proverb/create">Create Proverb</Link>
            </li>
          </ul>
        </header>
        <main>
        {children}
        </main>
        <Analytics />
      </body>
    </html>
  );
}
